[mesh]
maxh = 0.1

[data_gen]
tol = 1e-10
iterations = 50
is_complex = false
n_samples = 5_000
use_restricted_operator = false

[model]
compression_factor = 3
seed = 42
init_encoder_type = "glorot_uniform"
init_decoder_type = "glorot_uniform"

[model.init_encoder_kwargs]
# Here we can specify the kwargs for the encoder initialization

[model.init_decoder_kwargs]
# Here we can specify the kwargs for the decoder initialization
# value = 0.0

[optimization]
optimizer_type = "adam"
ord = 2
reg = 0.05

[optimization.optimizer_kwargs]
# Here we can specify the kwargs for the optimizer
learning_rate = 0.0005

[training]
n_epochs = 500
batch_size = 50
freq = 10

[solver]
solver_tol = 1e-10
solver_max_iter = 10_000

[smoother]
smoother_tol = 1e-10
smoother_max_iter = 50

[coarsening]
# "dec-dec", "dec-enc", "enc-enc", "enc-dec"
coarsening_type = "enc-enc"
use_restricted_operator = true
regularization = 0.001

[output]
save_weights = false
plot_weights = false
strict_assert = true
